name: Re-Useable Tests
on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      blender-version:
        required: true
        type: string
      runner-os:
        required: true
        type: string
      addon-id:
        required: true
        type: string
      base:
        required: true
        type: string
      extra:
        required: false
        type: string

    secrets:
      GH_PAT:
        required: true

jobs:
  test:
    timeout-minutes: 30
    name: Tests
    runs-on: ${{ inputs.runner-os }}
    env:
      PYTHONUNBUFFERED: 1
      CHARACTER_DNA_DEV: 1
      CHARACTER_CONTROL_RIG_DEV: 1
      RUNNING_CI: 1

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6
        with:
          path: ${{ inputs.base }}-addon
          lfs: true
          submodules: true
          token: ${{ secrets.GH_PAT }}

      - name: Checkout ${{ inputs.base }}-bindings Repo
        uses: actions/checkout@v6
        with:
          repository: "poly-hammer/${{ inputs.base }}-bindings"
          path: "${{ inputs.base }}-bindings"
          token: ${{ secrets.GH_PAT }}

      - name: Checkout ${{ inputs.base }}-core Repo
        uses: actions/checkout@v6
        with:
          repository: "poly-hammer/${{ inputs.base }}-core"
          path: "${{ inputs.base }}-core"
          token: ${{ secrets.GH_PAT }}

      # Only checkout the extra repo if it's specified
      # This addon uses the base addon as a dependency, 
      # so we need to have it checked out to run the tests.
      - name: Checkout Extra Repo
        if: inputs.extra != ''
        uses: actions/checkout@v6
        with:
          path: ${{ inputs.extra }}-addon
          lfs: true
          submodules: true
          token: ${{ secrets.GH_PAT }}

      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "latest"

      - name: Install Dependencies
        run: |
          cd ${{ inputs.extra || inputs.base }}-addon
          uv sync --python ${{ inputs.python-version }}
          uv pip install --upgrade bpy==${{ inputs.blender-version }}.*

      - name: Run Tests
        shell: bash
        env:
          PYTHONWARNINGS: ignore
        run: |
          cd ${{ inputs.extra || inputs.base }}-addon
          uv run --no-sync --python ${{ inputs.python-version }} pytest --cov-branch --cov-config=.coveragerc --cov=src/addons/${{ inputs.addon-id }} --cov-report=xml:reports/coverage/results.xml || true

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./${{ inputs.extra || inputs.base }}-addon/reports/coverage/results.xml
          report_type: "coverage"

      - name: Upload test reports to Codecov
        uses: codecov/codecov-action@v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./${{ inputs.extra || inputs.base }}-addon/reports/pytest/results.xml
          report_type: "test_results"

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v6
        # always run even if the previous step fails
        if: success() || failure()
        with:
          check_name: Test Results (${{ inputs.runner-os }} ${{ inputs.blender-version }})
          include_passed: False
          fail_on_failure: True
          require_tests: True
          require_passed_tests: True
          detailed_summary: False
          report_paths: "./${{ inputs.extra || inputs.base }}-addon/reports/pytest/*.xml"
